#include "PWM.h"
#include <xc.h>

void OC1_PWM(void){
TRISDbits.TRISD0=0;//oc1

/* t*FCY/PREESCALADOR -1 
 */


PR3=799;//TPWM=10 kHz
TMR3=0;//CONTADOR A 0
OC1R=0;//DUTY CYCLE INICIO 0 
OC1RS=0; 
OC1CONbits.OCM=0b110; //MODO PWM
OC1CONbits.OCTSEL=1;//ELEGIR TIMER 3
T3CONbits.TCKPS=0b10;//PRESCALER 1:1
T3CONbits.TCS=0; //ELEGIR FUENTE TCY
T3CONbits.TON=1; //COMENZAR A CONTAR
}
